### ISSUE TITLE
[question] Is there any example  How  should I  use sync_client in my project

### ISSUE THREAD

**Issue by iFlameing** [nponiros/sync_client#10]

**Comment by nponiros** [comment]
I used sync_client in https://github.com/nponiros/bookmarks_manager but it isn't a real example on how to use sync_client. Did you try integrating it by reading "Basic Usage" in the readme?

**Comment by iFlameing** [comment]
I make the use of sync client in my project can you provide me some documentation so that I can write the test for the database using jest . Right Now it is giving me error indexedDB API not found.

**Comment by nponiros** [comment]
I don’t use indexeddb in sync client directly. I use it via dexie. If I remember correctly jest runs in Node.js and not in the browser. I guess you would need to mock indexeddb. Maybe you can use 
https://github.com/dumbmatter/fakeIndexedDB for that. Unfortunatelly I have no example code for this.
