### ISSUE TITLE
Allow adding other addons

### ISSUE THREAD

**Issue by agkovalev** [nponiros/sync_client#5]
Hallo, tnx for nice lib. It would be also good, if in constructor could be passed some more addons, for example **"dexie-relationships".** 
Have a nice day!

**Comment by nponiros** [comment]
Hi there, I will try to do that tomorrow evening. Shouldn't take too much time.

**Comment by agkovalev** [comment]
Thank you for quick answer, I have just written 1 comment to the last commit with a simple code, that could be useful for this update.

**Comment by nponiros** [comment]
Fixed in https://github.com/nponiros/sync_client/commit/0078b9da6da092fbefe29f0b31e6b6bfa57509ee and published to npm as v1.0.0-beta.9. Checkout the readme for infos on how to pass the addons. If everything works as expected please close this issue. Thanks.

**Comment by agkovalev** [comment]
Thanks a lot, Nikolas!
