### ISSUE TITLE
Outdated version of Dexie.js

### ISSUE THREAD

**Issue by nevf** [nponiros/sync_client#7]
Package.json specifies ```"dependencies": { "dexie": "2.0.1", .. }``` which is out of date with the current Dexie V2.0.2 release and causing conflicting versions of Dexie.js to be used and app code to break.

**Comment by nponiros** [comment]
Thanks for the info. Will update as soon as possible.

**Comment by nevf** [comment]
No problem. I wonder if you can just make the dependency on V2 instead of 2.x

You maybe interested in this https://github.com/dfahlander/Dexie.js/issues/694

**Comment by nponiros** [comment]
I published a new version with dexie 2.x.x as dependency. Closing this.
